### PR TITLE
Refactor SSL socket handling in h2csmuggler.py

### PR DESCRIPTION
**Pull request by xut-e**
ssl.wrap_socket() was removed in Python 3.12. Python’s docs explicitly say to use an SSLContext and then call context.wrap_socket(...) instead. They also note the old function was insecure because it didn’t send SNI and didn’t validate hostnames properly.

### CODE REVIEW

**Comment by xut-e** [comment]
Hi,

I tried to run the tool with Python 3.12 and encountered the following error:

AttributeError: module 'ssl' has no attribute 'wrap_socket'



This happens because `ssl.wrap_socket()` was removed in Python 3.12. The
recommended approach in the Python documentation is to create an
`SSLContext` and call `context.wrap_socket()` instead.

This PR refactors the TLS socket creation in `establish_tcp_connection()`
to use `SSLContext.wrap_socket()` so the tool works with Python 3.12+.

No other changes were made to the codebase.

Great tool, thanks for sharing it.
